from base_classes import EnvironmentalConditions

ORBITAL_PERIOD = 41237
SUNLIT_PERIOD = 29853

VENUS = EnvironmentalConditions("Venus", 2900, 2.7, 1, 1)
EARTH = EnvironmentalConditions("Earth", 1400, 2.7, 1, 1)
ENCELADUS = EnvironmentalConditions("Enceladus", 15, 2.7, ORBITAL_PERIOD, SUNLIT_PERIOD)

DARK_PERIOD = ORBITAL_PERIOD - SUNLIT_PERIOD
END_OF_SUNLIT_PERIOD = SUNLIT_PERIOD
END_OF_EARTH_COMMS = END_OF_SUNLIT_PERIOD + 4000
END_OF_ORBIT_ADJUSTMENT = END_OF_EARTH_COMMS + 1000
END_OF_PRE_COLLECT = END_OF_ORBIT_ADJUSTMENT + 4686
END_OF_COLLECT = END_OF_PRE_COLLECT + 1698
